name: CI on Pull Request

on:
  pull_request:
    branches: [ "main" ]  # Kích hoạt khi có PR vào nhánh main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Xóa các bước setup Node.js và npm install
      # Thêm các bước build/test phù hợp với ngôn ngữ của bạn
      - name: Run Tests (Python example)
        run: pytest  # Thay bằng lệnh test của bạn