name: CI on Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Chọn version Python phù hợp

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Nếu có file requirements.txt
          pip install pytest  # Cài đặt pytest

      - name: Run Tests
        run: pytest  # Hoặc lệnh cụ thể của bạn (vd: pytest tests/)